import {
  Badge,
  CircleUser,
  ClipboardCheck,
  DollarSign,
  FileCheck,
  FileText,
  HandCoins,
  House,
  LayoutDashboard,
  Megaphone,
  MessagesSquare,
  Settings,
  Users,
  X,
} from "lucide-react";
export const agencyMenu = (user) => [
  {
    id: 1,
    title: "Home",
    icon: <House />,
    link: "/",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 2,
    title: "Dashboard",
    icon: <LayoutDashboard />,
    link: "/agency",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 3,
    title: "My Profile",
    icon: <CircleUser />,
    link: "profile",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 4,
    title: "Create Ads(Recruiting)",
    icon: <Megaphone />,
    link: "ads",
    roles: ["Recruiting"],
  },
  // {
  //   id: 4099777,
  //   title: "Create Ads(Hajj & Umrah)",
  //   icon: <Megaphone />,
  //   link: "ads",
  // },
  {
    id: 4973341,
    title: "Create Ads(Student Consultancy)",
    icon: <Megaphone />,
    link: "ads/student-consultency",
    roles: ["Student"],
  },
  {
    id: 5,
    title: "My Ads",
    icon: <Megaphone />,
    link: `ads-list/${user?._id}`,
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 6,
    title: "Message",
    icon: <MessagesSquare />,
    link: "chatbox",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 7,
    title: "Our All File",
    icon: <FileText />,
    children: [
      // { id: 701, title: "All Customer", link: "all-customer" },
      { id: 702, title: "Applied Customer", link: "applied-customer" },
      // {
      //   id: 8,
      //   title: "Passport Request",
      //   children: [
      //     { id: 801, title: "Ready for Flight", link: "ready-for-flight2" },
      //     {
      //       id: 802,
      //       title: "Request for Passport",
      //       link: "request-passport",
      //     },
      //     { id: 803, title: "Failed Visa", link: "failed-visa" },
      //   ],
      // },
      { id: 703, title: "On The Way", link: "on-the-way" },
      { id: 704, title: "Receive Passport", link: "receive-passport" },
      { id: 705, title: "Under Processing", link: "under-processing" },
      { id: 706, title: "Visa Approved", link: "visa-approved" },
      { id: 707, title: "Rejected Visa", link: "rejected-visa" },
      { id: 708, title: "Ready For Flight", link: "ready-for-flight" },
      { id: 709, title: "Return Passport", link: "return-passport" },
      { id: 710, title: "Handover Passport", link: "handover-passport" },
      { id: 711, title: "Success File", link: "success-file" },
    ],
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 9,
    title: "My Flight Ticket",
    icon: <FileText />,
    link: "flight-ticket",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 10,
    title: "All Booking File",
    icon: <FileText />,
    children: [
      { id: 1001, title: "My Booking", link: "my-booking" },
      { id: 1002, title: "Under Processing", link: "under-processing" },
      { id: 1003, title: "Success File", link: "success-file" },
      { id: 1004, title: "Return Passport", link: "return-passport" },
    ],
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 11,
    title: "User",
    icon: <Users />,
    children: [
      { id: 1101, title: "Create User", link: "create-user" },
      { id: 1102, title: "Manage User", link: "manage-user" },
      { id: 1103, title: "User Activity", link: "user-activity" },
    ],
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 12,
    title: "Commission",
    icon: <ClipboardCheck />,
    link: "commission",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 13,
    title: "Check Status",
    icon: <Badge />,
    link: "check-status",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 14,
    title: "Payment Details",
    icon: <HandCoins />,
    link: "payment-details",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 15,
    title: "Payment",
    icon: <DollarSign />,
    children: [
      { id: 1501, title: "Advance Payement", link: "advance-payment" },
      { id: 1502, title: "After Payment", link: "after-flight-payment" },
      { id: 1503, title: "Befor Payemnt", link: "befor-flight-payment" },
    ],
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 16,
    title: "Change Password",
    icon: <Settings />,
    link: "change-password",
    roles: ["Recruiting", "Hajj", "Student"],
  },
  {
    id: 17,
    title: "Terms and Condition",
    icon: <FileCheck />,
    link: "terms",
    roles: ["Recruiting", "Hajj", "Student"],
  },
];
