export const currencyList = [
  {
    code: "USD",
    symbol: "$",
    name: "United States Dollar",
    flag: "US",
    decimals: 2,
  },
  { code: "EUR", symbol: "€", name: "Euro", flag: "EU", decimals: 2 },
  {
    code: "GBP",
    symbol: "£",
    name: "British Pound Sterling",
    flag: "GB",
    decimals: 2,
  },
  { code: "JPY", symbol: "¥", name: "Japanese Yen", flag: "JP", decimals: 0 },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan", flag: "CN", decimals: 2 },
  { code: "INR", symbol: "₹", name: "Indian Rupee", flag: "IN", decimals: 2 },
  {
    code: "BDT",
    symbol: "৳",
    name: "Bangladeshi Taka",
    flag: "BD",
    decimals: 2,
  },
  {
    code: "PKR",
    symbol: "Rs",
    name: "Pakistani Rupee",
    flag: "PK",
    decimals: 2,
  },
  {
    code: "AUD",
    symbol: "A$",
    name: "Australian Dollar",
    flag: "AU",
    decimals: 2,
  },
  {
    code: "CAD",
    symbol: "C$",
    name: "Canadian Dollar",
    flag: "CA",
    decimals: 2,
  },
  {
    code: "NZD",
    symbol: "NZ$",
    name: "New Zealand Dollar",
    flag: "NZ",
    decimals: 2,
  },
  {
    code: "SGD",
    symbol: "S$",
    name: "Singapore Dollar",
    flag: "SG",
    decimals: 2,
  },
  {
    code: "HKD",
    symbol: "HK$",
    name: "Hong Kong Dollar",
    flag: "HK",
    decimals: 2,
  },
  { code: "CHF", symbol: "CHF", name: "Swiss Franc", flag: "CH", decimals: 2 },
  { code: "SEK", symbol: "kr", name: "Swedish Krona", flag: "SE", decimals: 2 },
  {
    code: "NOK",
    symbol: "kr",
    name: "Norwegian Krone",
    flag: "NO",
    decimals: 2,
  },
  { code: "DKK", symbol: "kr", name: "Danish Krone", flag: "DK", decimals: 2 },
  { code: "RUB", symbol: "₽", name: "Russian Ruble", flag: "RU", decimals: 2 },
  {
    code: "BRL",
    symbol: "R$",
    name: "Brazilian Real",
    flag: "BR",
    decimals: 2,
  },
  {
    code: "ZAR",
    symbol: "R",
    name: "South African Rand",
    flag: "ZA",
    decimals: 2,
  },
  { code: "MXN", symbol: "MX$", name: "Mexican Peso", flag: "MX", decimals: 2 },
  { code: "TRY", symbol: "₺", name: "Turkish Lira", flag: "TR", decimals: 2 },
  { code: "PLN", symbol: "zł", name: "Polish Złoty", flag: "PL", decimals: 2 },
  {
    code: "IDR",
    symbol: "Rp",
    name: "Indonesian Rupiah",
    flag: "ID",
    decimals: 2,
  },
  {
    code: "MYR",
    symbol: "RM",
    name: "Malaysian Ringgit",
    flag: "MY",
    decimals: 2,
  },
  { code: "THB", symbol: "฿", name: "Thai Baht", flag: "TH", decimals: 2 },
  {
    code: "VND",
    symbol: "₫",
    name: "Vietnamese Dong",
    flag: "VN",
    decimals: 0,
  },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham", flag: "AE", decimals: 2 },
  { code: "SAR", symbol: "﷼", name: "Saudi Riyal", flag: "SA", decimals: 2 },
  {
    code: "ILS",
    symbol: "₪",
    name: "Israeli New Shekel",
    flag: "IL",
    decimals: 2,
  },
  {
    code: "HUF",
    symbol: "Ft",
    name: "Hungarian Forint",
    flag: "HU",
    decimals: 2,
  },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna", flag: "CZ", decimals: 2 },
  {
    code: "UAH",
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    flag: "UA",
    decimals: 2,
  },
  { code: "CLP", symbol: "$", name: "Chilean Peso", flag: "CL", decimals: 0 },
  {
    code: "EGP",
    symbol: "E£",
    name: "Egyptian Pound",
    flag: "EG",
    decimals: 2,
  },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira", flag: "NG", decimals: 2 },
  { code: "ARS", symbol: "$", name: "Argentine Peso", flag: "AR", decimals: 2 },
  { code: "COP", symbol: "$", name: "Colombian Peso", flag: "CO", decimals: 2 },
  {
    code: "KRW",
    symbol: "₩",
    name: "South Korean Won",
    flag: "KR",
    decimals: 0,
  },
  { code: "KWD", symbol: "KD", name: "Kuwaiti Dinar", flag: "KW", decimals: 3 },
];
