export const data = [
  {
    id: 1,
    title: "Construction Worker",
    countryName: "Saudi Arabia",
    typeOfWork: "Labor",
    visaBanner:
      "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=944&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Al Jazeera Constructions",
    companyLocation: "Riyadh",
    visaSponsorName: "Al Jazeera Group",
    selectionCategory: "Direct Interview",
    typeOfVisa: "Work Visa",
    salary: "1200 SAR",
    ageLimit: "21-40",
    iqamaExpenses: "Company Provided",
    foodExpenses: "Self",
    WorkingHours: "8 hours/day",
    TotalQouta: 25,
    durationEmployment: "2 Years",
    accommodation: "Company Provided",
    gender: "Male",
    requiredDocuments: ["Passport", "Photo", "CV"],
    packageInclude: ["Visa", "Ticket", "Medical"],
    expriencesNeed: "No experience required",
    deadline: "2025-10-30",
    delegateDate: "2025-11-05",
    totalPrice: "3,50,000 BDT",
    totalPriceWithCommision: "3,80,000 BDT",
    paymentSystem: "2 Installments",
    description:
      "Urgent demand for construction workers with attractive benefits.",
  },
  {
    id: 2,
    title: "Cleaner",
    countryName: "Dubai, UAE",
    typeOfWork: "Housekeeping",
    visaBanner:
      "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Dubai Clean Services",
    companyLocation: "Dubai",
    visaSponsorName: "Dubai HR",
    selectionCategory: "CV Selection",
    typeOfVisa: "Work Visa",
    salary: "1000 AED",
    ageLimit: "20-38",
    iqamaExpenses: "N/A",
    foodExpenses: "Company Provided",
    WorkingHours: "9 hours/day",
    TotalQouta: 40,
    durationEmployment: "2 Years",
    accommodation: "Company Provided",
    gender: "Female",
    requiredDocuments: ["Passport", "Photo", "Medical Report"],
    packageInclude: ["Visa", "Accommodation", "Food"],
    expriencesNeed: "Basic cleaning experience preferred",
    deadline: "2025-11-10",
    delegateDate: "2025-11-20",
    totalPrice: "2,80,000 BDT",
    totalPriceWithCommision: "3,00,000 BDT",
    paymentSystem: "Full Advance",
    description: "Vacancy for female cleaners in Dubai hotels and households.",
  },
  {
    id: 3,
    title: "Driver",
    countryName: "Qatar",
    typeOfWork: "Driving",
    visaBanner:
      "https://images.unsplash.com/photo-1444084316824-dc26d6657664?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Qatar Transport Co.",
    companyLocation: "Doha",
    visaSponsorName: "Qatar Transport Authority",
    selectionCategory: "Direct Interview",
    typeOfVisa: "Work Visa",
    salary: "1800 QAR",
    ageLimit: "23-42",
    iqamaExpenses: "Company Provided",
    foodExpenses: "Self",
    WorkingHours: "8 hours/day + Overtime",
    TotalQouta: 15,
    durationEmployment: "2 Years",
    accommodation: "Company Provided",
    gender: "Male",
    requiredDocuments: ["Passport", "Driving License", "Photo"],
    packageInclude: ["Visa", "Ticket", "Accommodation"],
    expriencesNeed: "2 years driving experience",
    deadline: "2025-10-25",
    delegateDate: "2025-11-02",
    totalPrice: "4,20,000 BDT",
    totalPriceWithCommision: "4,50,000 BDT",
    paymentSystem: "3 Installments",
    description: "Qatar driving job for light and heavy vehicle drivers.",
  },
  {
    id: 4,
    title: "Electrician",
    countryName: "Oman",
    typeOfWork: "Technical",
    visaBanner:
      "https://images.unsplash.com/photo-1535090467336-9501f96eef89?q=80&w=900&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Muscat Electricals",
    companyLocation: "Muscat",
    visaSponsorName: "Oman HR Solutions",
    selectionCategory: "Trade Test",
    typeOfVisa: "Work Visa",
    salary: "160 OMR",
    ageLimit: "22-38",
    iqamaExpenses: "Company Provided",
    foodExpenses: "Company Provided",
    WorkingHours: "8 hours/day",
    TotalQouta: 10,
    durationEmployment: "2 Years",
    accommodation: "Company Provided",
    gender: "Male",
    requiredDocuments: ["Passport", "Experience Certificate", "Photo"],
    packageInclude: ["Visa", "Accommodation", "Food", "Ticket"],
    expriencesNeed: "Minimum 2 years electrician experience",
    deadline: "2025-11-15",
    delegateDate: "2025-11-22",
    totalPrice: "3,80,000 BDT",
    totalPriceWithCommision: "4,00,000 BDT",
    paymentSystem: "Full Payment",
    description:
      "Electricians required in Oman with good salary and facilities.",
  },
  {
    id: 5,
    title: "Nurse",
    countryName: "Kuwait",
    typeOfWork: "Medical",
    visaBanner:
      "https://images.unsplash.com/photo-1590105577767-e21a1067899f?q=80&w=1528&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Kuwait Medical Center",
    companyLocation: "Kuwait City",
    visaSponsorName: "Kuwait Healthcare Group",
    selectionCategory: "CV Selection + Interview",
    typeOfVisa: "Work Visa",
    salary: "250 KD",
    ageLimit: "23-35",
    iqamaExpenses: "Company Provided",
    foodExpenses: "Self",
    WorkingHours: "8 hours/day",
    TotalQouta: 20,
    durationEmployment: "2 Years",
    accommodation: "Company Provided",
    gender: "Female",
    requiredDocuments: ["Passport", "Nursing Certificate", "Photo"],
    packageInclude: ["Visa", "Ticket", "Accommodation"],
    expriencesNeed: "2 years hospital experience required",
    deadline: "2025-11-05",
    delegateDate: "2025-11-12",
    totalPrice: "5,00,000 BDT",
    totalPriceWithCommision: "5,50,000 BDT",
    paymentSystem: "2 Installments",
    description: "Urgent requirement for female nurses in Kuwait hospitals.",
  },
  {
    id: 6,
    title: "Bachelor in Computer Science",
    countryName: "Canada",
    typeOfWork: "Study",
    visaBanner:
      "https://images.unsplash.com/photo-1553893304-448dd3e66fd1?q=80&w=869&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "University of Toronto",
    companyLocation: "Toronto",
    visaSponsorName: "Canadian Embassy",
    selectionCategory: "CV + Academic Background",
    typeOfVisa: "Student Visa",
    salary: "N/A",
    ageLimit: "18-30",
    iqamaExpenses: "N/A",
    foodExpenses: "Self",
    WorkingHours: "20 hours/week (part-time allowed)",
    TotalQouta: 50,
    durationEmployment: "4 Years",
    accommodation: "University Dormitory",
    gender: "Male/Female",
    requiredDocuments: [
      "Passport",
      "Academic Certificate",
      "IELTS Score",
      "Bank Statement",
    ],
    packageInclude: ["Visa Processing", "Admission Letter", "Medical"],
    expriencesNeed: "Not required",
    deadline: "2025-12-15",
    delegateDate: "2026-01-05",
    totalPrice: "12,00,000 BDT",
    totalPriceWithCommision: "12,50,000 BDT",
    paymentSystem: "Installments Available",
    description:
      "Bachelor program in Computer Science with work opportunities.",
  },
  {
    id: 7,
    title: "Master in Business Administration (MBA)",
    countryName: "Australia",
    typeOfWork: "Study",
    visaBanner:
      "https://images.unsplash.com/photo-1662148931823-b0f72b89a6fc?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "University of Melbourne",
    companyLocation: "Melbourne",
    visaSponsorName: "Australian Embassy",
    selectionCategory: "Academic + Interview",
    typeOfVisa: "Student Visa",
    salary: "N/A",
    ageLimit: "22-35",
    iqamaExpenses: "N/A",
    foodExpenses: "Self",
    WorkingHours: "20 hours/week (part-time allowed)",
    TotalQouta: 30,
    durationEmployment: "2 Years",
    accommodation: "Hostel / Private",
    gender: "Male/Female",
    requiredDocuments: [
      "Passport",
      "Bachelor Certificate",
      "IELTS/TOEFL Score",
      "Bank Statement",
    ],
    packageInclude: ["Visa", "Admission", "Medical Insurance"],
    expriencesNeed: "2 years job experience preferred",
    deadline: "2025-11-30",
    delegateDate: "2026-01-10",
    totalPrice: "15,00,000 BDT",
    totalPriceWithCommision: "15,50,000 BDT",
    paymentSystem: "Full or Installments",
    description: "MBA program with internship opportunities in top companies.",
  },
  {
    id: 8,
    title: "Diploma in Hotel Management",
    countryName: "Malaysia",
    typeOfWork: "Study",
    visaBanner:
      "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Kuala Lumpur Hospitality Institute",
    companyLocation: "Kuala Lumpur",
    visaSponsorName: "Malaysia Embassy",
    selectionCategory: "Direct Admission",
    typeOfVisa: "Student Visa",
    salary: "N/A",
    ageLimit: "18-32",
    iqamaExpenses: "N/A",
    foodExpenses: "Self",
    WorkingHours: "20 hours/week",
    TotalQouta: 40,
    durationEmployment: "2 Years",
    accommodation: "Institute Hostel",
    gender: "Male/Female",
    requiredDocuments: ["Passport", "SSC/HSC Certificate", "Bank Statement"],
    packageInclude: ["Visa", "Admission", "Medical Insurance"],
    expriencesNeed: "Not required",
    deadline: "2025-12-20",
    delegateDate: "2026-01-15",
    totalPrice: "6,50,000 BDT",
    totalPriceWithCommision: "7,00,000 BDT",
    paymentSystem: "Easy Installments",
    description: "2 years diploma with part-time job options in Malaysia.",
  },
  {
    id: 9,
    title: "Bachelor in Mechanical Engineering",
    countryName: "Germany",
    typeOfWork: "Study",
    visaBanner:
      "https://images.unsplash.com/photo-1620831468075-db24ca183258?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Technical University of Munich",
    companyLocation: "Munich",
    visaSponsorName: "German Embassy",
    selectionCategory: "Academic + IELTS",
    typeOfVisa: "Student Visa",
    salary: "N/A",
    ageLimit: "18-28",
    iqamaExpenses: "N/A",
    foodExpenses: "Self",
    WorkingHours: "20 hours/week",
    TotalQouta: 25,
    durationEmployment: "4 Years",
    accommodation: "University Dorm",
    gender: "Male/Female",
    requiredDocuments: [
      "Passport",
      "Academic Certificate",
      "Language Proficiency",
      "Bank Statement",
    ],
    packageInclude: ["Visa", "Admission", "Insurance"],
    expriencesNeed: "Not required",
    deadline: "2025-12-05",
    delegateDate: "2026-01-20",
    totalPrice: "10,00,000 BDT",
    totalPriceWithCommision: "10,50,000 BDT",
    paymentSystem: "Full Payment",
    description: "Germany Engineering program with scholarship opportunities.",
  },
  {
    id: 10,
    title: "Master in Data Science",
    countryName: "UK",
    typeOfWork: "Study",
    visaBanner:
      "https://images.unsplash.com/photo-1758270704840-0ac001215b55?q=80&w=1031&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "University of Manchester",
    companyLocation: "Manchester",
    visaSponsorName: "UK Embassy",
    selectionCategory: "Academic + Interview",
    typeOfVisa: "Student Visa",
    salary: "N/A",
    ageLimit: "21-35",
    iqamaExpenses: "N/A",
    foodExpenses: "Self",
    WorkingHours: "20 hours/week",
    TotalQouta: 20,
    durationEmployment: "2 Years",
    accommodation: "University Hostel",
    gender: "Male/Female",
    requiredDocuments: [
      "Passport",
      "Bachelor Certificate",
      "IELTS/TOEFL Score",
      "Bank Statement",
    ],
    packageInclude: ["Visa", "Admission", "Medical"],
    expriencesNeed: "Basic IT/Programming knowledge required",
    deadline: "2025-11-25",
    delegateDate: "2026-01-12",
    totalPrice: "14,00,000 BDT",
    totalPriceWithCommision: "14,50,000 BDT",
    paymentSystem: "Installments Available",
    description:
      "Data Science Master's program with part-time work opportunities in UK.",
  },
  {
    id: 11,
    title: "Hajj Package 2025",
    countryName: "Saudi Arabia",
    typeOfWork: "Religious Pilgrimage",
    visaBanner:
      "https://images.unsplash.com/photo-1589827577276-65d717348780?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Al Haramain Travels",
    companyLocation: "Makkah & Madinah",
    visaSponsorName: "Saudi Hajj Ministry",
    selectionCategory: "Group Basis",
    typeOfVisa: "Hajj and umrah Visa",
    salary: "N/A",
    ageLimit: "18-65",
    iqamaExpenses: "N/A",
    foodExpenses: "Included in Package",
    WorkingHours: "N/A",
    TotalQouta: 200,
    durationEmployment: "40 Days",
    accommodation: "Hotel in Makkah & Madinah",
    gender: "Male/Female",
    requiredDocuments: ["Passport", "NID", "Photo", "Vaccination Certificate"],
    packageInclude: ["Visa", "Air Ticket", "Hotel", "Food", "Transport"],
    expriencesNeed: "Not Required",
    deadline: "2025-04-30",
    delegateDate: "2025-05-15",
    totalPrice: "4,50,000 BDT",
    totalPriceWithCommision: "4,80,000 BDT",
    paymentSystem: "2 Installments",
    description:
      "Complete Hajj package with hotel, transport, and food facilities included.",
  },
  {
    id: 12,
    title: "Umrah Package 2025",
    countryName: "Saudi Arabia",
    typeOfWork: "Religious Pilgrimage",
    visaBanner:
      "https://images.unsplash.com/photo-1633174754673-95dd2842f8fc?q=80&w=1031&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    companyName: "Darussalam Travels",
    companyLocation: "Makkah & Madinah",
    visaSponsorName: "Saudi Umrah Authority",
    selectionCategory: "Direct Application",
    typeOfVisa: "Hajj and umrah Visa",
    salary: "N/A",
    ageLimit: "18-65",
    iqamaExpenses: "N/A",
    foodExpenses: "Optional (Self/Package)",
    WorkingHours: "N/A",
    TotalQouta: 500,
    durationEmployment: "15 Days",
    accommodation: "3 Star/5 Star Hotels",
    gender: "Male/Female",
    requiredDocuments: ["Passport", "Photo", "NID"],
    packageInclude: ["Visa", "Air Ticket", "Hotel", "Transport"],
    expriencesNeed: "Not Required",
    deadline: "2025-11-20",
    delegateDate: "2025-12-01",
    totalPrice: "1,80,000 BDT",
    totalPriceWithCommision: "2,00,000 BDT",
    paymentSystem: "Full Payment",
    description: "Affordable Umrah package with hotel and transport service.",
  },
];
